pr: none

trigger:
  branches:
    include:
    - main
    
pool:
  name: Azure Pipelines
  vmImage: windows-2019

workspace:
    clean: all

variables:
  - name: CONTAINER_LABEL
    value: devops-challenge-deploy-agent
  - template: variables.yml

steps:

  - task: DotNetCoreCLI@2
    displayName: Build Solution

  - task: DotNetCoreCLI@2
    displayName: Unit Test
    inputs:
      command: test
      projects: '**/*.csproj'
    continueOnError: true

  - task: PowerShell@2
    displayName: Create Docker Image
    displayName: 'PowerShell Script'
    inputs:
      targetType: filePath
      filePath: $(System.DefaultWorkingDirectory)\build.ps1
      arguments: -CONTAINER_LABEL $(CONTAINER_LABEL)

  - task: Docker@2
    displayName: Build and push image to container registry
    inputs:
      command: buildAndPush
      containerRegistry: '${{ variables.containerRegistryServiceConnectionName }}'
      repository: $(CONTAINER_LABEL)
      Dockerfile: Dockerfile
      tags: latest