pr: none

trigger: none
    
pool:
  name: Azure Pipelines
  vmImage: windows-2019

workspace:
    clean: all

variables:
  - name: CONTAINER_LABEL
    value: devops-challenge-deploy-agent
  - template: variables.yml

steps:

  - task: DotNetCoreCLI@2
    displayName: Build

  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: test
      projects: '**/*.csproj'
    continueOnError: true

  - task: PowerShell@2
    displayName: 'PowerShell Script'
    inputs:
      targetType: filePath
      workingDirectory: DEVOPS
      filePath: DEVOPS/build.ps1
      arguments: -CONTAINER_LABEL $(CONTAINER_LABEL)

  - task: Docker@2
    displayName: Build and push image to container registry
    inputs:
      command: buildAndPush
      containerRegistry: '${{ variables.containerRegistryServiceConnectionName }}'
      repository: $(CONTAINER_LABEL)
      Dockerfile: Dockerfile
      tags: latest
      buildContext: DEVOPS

#pool:
#  name: Azure Pipelines
#
#steps:
#- task: DotNetCoreCLI@2
#  displayName: Build
#
#- task: DotNetCoreCLI@2
#  displayName: Test
#  inputs:
#    command: test
#    projects: '**/*.csproj'
#  continueOnError: true
#
#- task: NuGetCommand@2
#  displayName: 'Create Package'
#  inputs:
#    command: pack
#
#- task: PublishBuildArtifacts@1
#  displayName: PublishArtifacts
#
#- task: DockerInstaller@0
#  displayName: 'Install Docker 17.09.0-ce'
#
#- task: Docker@2
#  displayName: buildAndPush
#  inputs:
#    containerRegistry: msacrconn
#    repository: '$(Parameters.repository)'
#    Dockerfile: DockerFile