version: '3.4'

services:
  devopschallengesalesapi:
    image: devopschallengesalesapi
    build:
      context: .
      dockerfile: src/DevOpsChallenge.SalesApi/Dockerfile
    ports:
      - 5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    volumes:
      - ~/.vsdbg:c:\remote_debugger:rw
